# Rules to monitor sync of ExternalSecret object
#  via Kubernetes External Secrets
#
# Required customizations
#   - Set ci_name to a UW Connect CI that matches your group
#   - Set focus to desired value for rule.

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-exsecret-rules
  namespace: default
  labels:
    prometheus: k8s
    role: alert-rules

spec:
  groups:
  - name: externalsecrets
    rules:
    - alert: SecretSyncError
      annotations:
        summary: SecretSyncError {{ $labels.name }}
        description: |
          Synchronization of the Secret {{ $labels.name }} in namespace {{ $labels.exported_namespace }} is failing.
          Check for errors in the Status field of the associated ExternalSecret object.
      expr: increase(sync_calls{exported_namespace=~"default|anothernamespace",status="error"}[2m]) > 0 
      for: 5m
      labels:
        ci_name: YourConfigurationItemHere
        alert_notify: "true"
        focus: "3"
        
---
# This rule is for ESO Secrets
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-exsecret-rules
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
  - name: externalsecrets
    rules:
    - alert: ExternalSecretSyncError
      annotations:
        summary: SecretSyncError {{ $labels.name }}
        description: |
          Synchronization of the Secret {{ $labels.name }} in namespace {{ $labels.exported_namespace }} is failing.
          Check for errors in the Status field of the associated ExternalSecret object.
          See: https://wiki.cac.washington.edu/x/ysnFBg
      expr: increase(externalsecret_sync_calls_error{exported_namespace=~"default|anothernamespace"}[5m]) > 0 
      for: 10m
      labels:
        ci_name: YourConfigurationItemHere
        alert_notify: "true"
        focus: "3"
        
