---
# Rules to monitor sync of ExternalSecret object
#  via External Secrets Operator
#
# Required customizations
#   - Set ci_name to a UW Connect CI that matches your group
#   - Set focus to desired value for rule.

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-exsecret-rules
  labels:
    prometheus: k8s
    role: alert-rules
spec:
  groups:
  - name: externalsecrets
    rules:
    - alert: ExternalSecretSyncError
      annotations:
        summary: ExternalSecret Sync Error {{ $labels.name }}
        description: |
          Synchronization of the Secret {{ $labels.name }} in namespace {{ $labels.exported_namespace }} is failing.
          Check for errors in the Status field of the associated ExternalSecret object.
          `kubectl describe externalsecret {{ $labels.name }} -n {{ $labels.exported_namespace }}`
      expr: externalsecret_status_condition{exported_namespace=~"cert-manager|ingress-nginx|mci-.+",status="False"} == 1
      for: 2h  # ExternalSecret refresh interval is 1h so we wait for 2h to make sure it's not a transient error
      labels:
        ci_name: YourConfigurationItemHere
        alert_notify: "true"
        focus: "3"
        
