# Rules to monitor sync of ExternalSecret object
#  via Kubernetes External Secrets
#
# Required customizations
#   - Set ci_name to a UW Connect CI that matches your group
#   - Set focus to desired value for rule.

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-exsecret-rules
  namespace: default
  labels:
    prometheus: k8s
    role: alert-rules

spec:
  groups:
  - name: externalsecrets
    rules:
    - alert: SecretSyncError
      annotations:
        summary: SecretSyncError {{ $labels.name }}
        description: |
          Synchronization of the Secret {{ $labels.name }} in namespace {{ $labels.exported_namespace }} is failing.
          Check for errors in the Status field of the associated ExternalSecret object.
      expr: last_state{exported_namespace=~"default|anothernamespace"} < 0
      for: 5m
      labels:
        ci_name: YourConfigurationItemHere
        alert_notify: "true"
        focus: "3"