---
# Ingress for myapp3
# Requires SAML, with group u_othergroup
# Does not use rewrite
# Passes X-SAML-User auth header to backend as Remote-User header
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: server1-myapp3
  namespace: mci-monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/saml/status/group/u_othergroup"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/saml/login$request_uri"
    nginx.ingress.kubernetes.io/auth-snippet: |
      auth_request_set $auth_user $upstream_http_x_saml_user;
      proxy_set_header Remote-User $auth_user;
spec:
  rules:
  - host: server1.example.uw.edu
    http:
      paths:
      - path: /myapp3
        backend:
          serviceName: myapp3
          servicePort: http

